
import React, { useState, useEffect } from 'react';
import { Sparkles, TrendingUp, Target, Lightbulb, RefreshCw, AlertCircle } from 'lucide-react';
import { getBusinessInsights } from '../services/geminiService';
import { InsightReport, Product, Order } from '../types';

interface AIInsightsProps {
  products: Product[];
  orders: Order[];
}

export const AIInsights: React.FC<AIInsightsProps> = ({ products, orders }) => {
  const [loading, setLoading] = useState(true);
  const [insights, setInsights] = useState<InsightReport | null>(null);

  const fetchInsights = async () => {
    setLoading(true);
    const data = await getBusinessInsights({
      totalRevenue: orders.reduce((acc, curr) => acc + curr.amount, 0),
      totalOrders: orders.length,
      totalCustomers: orders.length, 
      activeProducts: products.length,
      revenueGrowth: 0,
      orderGrowth: 0
    });
    setInsights(data);
    setLoading(false);
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  return (
    <div className="space-y-8 animate-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-black text-indigo-950 flex items-center gap-3">
            Predictive Business Intelligence
            <span className="px-2 py-0.5 bg-indigo-900 text-white text-[9px] uppercase font-black rounded tracking-widest">Enterprise Logic</span>
          </h1>
          <p className="text-slate-500 mt-1">Advanced roadmap and analysis generated by BharatCart Smart Logic.</p>
        </div>
        <button 
          onClick={fetchInsights}
          disabled={loading}
          className="flex items-center gap-2 px-5 py-2.5 bg-black text-white rounded-xl font-black hover:bg-slate-900 transition-all disabled:opacity-50 text-[10px] uppercase tracking-widest shadow-xl shadow-black/10"
        >
          <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
          {loading ? 'Analyzing...' : 'Re-calculate Strategy'}
        </button>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-40 space-y-6">
          <div className="relative">
            <div className="w-20 h-20 border-4 border-slate-100 border-t-indigo-950 rounded-full animate-spin"></div>
            <Sparkles className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-indigo-950" size={32} />
          </div>
          <div className="text-center">
            <p className="text-indigo-950 font-black text-xl tracking-tight">Processing Store Analytics...</p>
            <p className="text-slate-500 font-medium">Running merchant logic against regional trade data.</p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <section className="bg-white p-10 rounded-[3rem] border border-slate-100 shadow-2xl shadow-slate-200/50">
              <div className="flex items-center gap-3 mb-8">
                <div className="p-4 bg-indigo-950 rounded-2xl">
                  <TrendingUp size={28} className="text-orange-400" />
                </div>
                <h2 className="text-2xl font-black text-indigo-950 tracking-tight">Market Analysis Report</h2>
              </div>
              <p className="text-slate-600 leading-relaxed text-lg font-medium">
                {products.length === 0 
                  ? "As a new merchant node, initial system focus is on SKU ingestion. We recommend prioritizing high-margin ethnic handicrafts for the upcoming quarterly cycle."
                  : insights?.summary}
              </p>
            </section>

            <section className="bg-white p-10 rounded-[3rem] border border-slate-100 shadow-2xl shadow-slate-200/50">
              <div className="flex items-center gap-3 mb-8">
                <div className="p-4 bg-emerald-600 rounded-2xl">
                  <Target size={28} className="text-white" />
                </div>
                <h2 className="text-2xl font-black text-indigo-950 tracking-tight">Growth Protocol</h2>
              </div>
              <div className="grid grid-cols-1 gap-4">
                {(products.length === 0 
                  ? ["Register unique SKUs with HSN-compliant metadata.", "Establish UPI VPA connectivity for immediate liquidation.", "Ingest high-resolution imagery for consumer trust mapping."]
                  : insights?.recommendations || []).map((rec, i) => (
                  <div key={i} className="flex gap-6 p-6 rounded-[2rem] bg-slate-50 border border-slate-100 group">
                    <div className="flex-shrink-0 w-12 h-12 rounded-2xl bg-white text-indigo-950 flex items-center justify-center font-black shadow-sm group-hover:bg-indigo-950 group-hover:text-white transition-all">
                      {i + 1}
                    </div>
                    <p className="text-indigo-950 font-bold text-lg leading-snug">{rec}</p>
                  </div>
                ))}
              </div>
            </section>
          </div>

          <div className="space-y-8">
            <section className="bg-indigo-950 text-white p-10 rounded-[3rem] shadow-2xl shadow-indigo-900/20">
              <div className="flex items-center gap-3 mb-8">
                <Lightbulb size={28} className="text-orange-400" />
                <h2 className="text-2xl font-black tracking-tight">Logic Watch</h2>
              </div>
              <div className="space-y-4">
                <p className="text-indigo-300 text-[10px] font-black uppercase tracking-widest">Trending Categories</p>
                {insights?.trendingCategories.map((cat, i) => (
                  <div key={i} className="px-5 py-4 bg-white/5 rounded-2xl border border-white/10 flex items-center justify-between">
                    <span className="font-black text-lg">{cat}</span>
                    <TrendingUp size={18} className="text-emerald-400" />
                  </div>
                ))}
              </div>
              <div className="mt-12 pt-6 border-t border-white/5 opacity-50">
                <p className="text-[10px] text-indigo-400 font-black uppercase tracking-widest">
                  Enterprise Analysis Engine v2.4
                </p>
              </div>
            </section>

            {products.length > 0 && products.some(p => p.stock < 10) && (
              <section className="bg-orange-50 p-10 rounded-[3rem] border border-orange-100">
                <div className="flex items-center gap-3 mb-4 text-orange-600">
                  <AlertCircle size={24} />
                  <h3 className="font-black text-lg uppercase tracking-tight">Stock Protocol</h3>
                </div>
                <p className="text-slate-700 font-bold leading-relaxed text-sm">
                  System predicts imminent stock-out. Execute replenishment protocol for critical SKUs.
                </p>
                <button className="w-full mt-8 py-4 bg-orange-600 text-white font-black rounded-2xl hover:bg-orange-700 transition-all uppercase tracking-widest text-[10px]">
                  Execute Restock
                </button>
              </section>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
